services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    container_name: app
    env_file:
      - .env

  postgres:
    image: "postgres:bookworm"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  vault:
    privileged: true
    image: "hashicorp/vault"
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    volumes:
      - vault_data:/vault/file
      - vault_logs:/vault/logs
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    command: vault server -config=/vault/config


volumes:
  pgdata:
  vault_data:
  vault_logs:
  vault_config:
    